#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        deb-systemd-helper stop cdi-mp.service >/dev/null 2>&1 || true
        deb-systemd-helper disable cdi-mp.service >/dev/null 2>&1 || true
        ;;
    upgrade)
        deb-systemd-helper stop cdi-mp.service >/dev/null 2>&1 || true
        ;;
    failed-upgrade)
        exit 0
        ;;
    *)
        exit 0
        ;;
esac

exit 0
